-- MySQL Script generated by MySQL Workbench
-- 06/27/16 14:43:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sicvigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sicvigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sicvigo` DEFAULT CHARACTER SET utf8 ;
USE `sicvigo` ;

-- -----------------------------------------------------
-- Table `sicvigo`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicvigo`.`setor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(100) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `ramal` TINYTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicvigo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicvigo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `email` VARCHAR(100) NULL,
  `tipo` VARCHAR(3) NULL DEFAULT 'usr',
  `setor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `setor_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_usuario_setor_idx` (`setor_id` ASC),
  CONSTRAINT `fk_usuario_setor`
    FOREIGN KEY (`setor_id`)
    REFERENCES `sicvigo`.`setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicvigo`.`natureza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicvigo`.`natureza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `natureza` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sicvigo`.`chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sicvigo`.`chamado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` MEDIUMTEXT NULL,
  `anotacao` MEDIUMTEXT NULL,
  `atribuicao` VARCHAR(100) NULL DEFAULT 'TI',
  `usuario_id` INT NOT NULL,
  `usuario_setor_id` INT NOT NULL,
  `natureza_id` INT NOT NULL,
  `situacao` VARCHAR(45) NOT NULL DEFAULT 'aberto',
  PRIMARY KEY (`id`, `usuario_id`, `usuario_setor_id`, `natureza_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_chamado_usuario1_idx` (`usuario_id` ASC, `usuario_setor_id` ASC),
  INDEX `fk_chamado_natureza1_idx` (`natureza_id` ASC),
  CONSTRAINT `fk_chamado_usuario1`
    FOREIGN KEY (`usuario_id` , `usuario_setor_id`)
    REFERENCES `sicvigo`.`usuario` (`id` , `setor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamado_natureza1`
    FOREIGN KEY (`natureza_id`)
    REFERENCES `sicvigo`.`natureza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
